21:30 10-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main 2f81048] 213010122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   5a5933e..2f81048  main -> main


22:00 10-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main 075e3d9] 220010122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   2f81048..075e3d9  main -> main


22:30 10-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main 65272a2] 223010122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   075e3d9..65272a2  main -> main


23:00 10-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main c24bd1e] 230010122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   65272a2..c24bd1e  main -> main


23:30 10-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main a0e61f5] 233010122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   c24bd1e..a0e61f5  main -> main


00:00 11-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main ce3e5ad] 000011122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   a0e61f5..ce3e5ad  main -> main


00:30 11-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main 559ab6b] 003011122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   ce3e5ad..559ab6b  main -> main


01:00 11-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main 7589aa9] 010011122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   559ab6b..7589aa9  main -> main


01:30 11-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main 85974ae] 013011122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   7589aa9..85974ae  main -> main


02:00 11-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main 278ff02] 020011122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   85974ae..278ff02  main -> main


02:30 11-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main d683e3f] 023011122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   278ff02..d683e3f  main -> main


03:00 11-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main 393c46e] 030011122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   d683e3f..393c46e  main -> main


03:30 11-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main 3ee1cf4] 033011122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   393c46e..3ee1cf4  main -> main


04:00 11-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main d503815] 040011122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   3ee1cf4..d503815  main -> main


04:30 11-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main 2c7565c] 043011122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   d503815..2c7565c  main -> main


05:00 11-12-2024

# Get in right directory

# Get up to date
Already up to date.

# Run main file

# Upload to Github
[main 258b621] 050011122024
 1 file changed, 300 insertions(+), 300 deletions(-)
To github.com:LaurensGamet/Somtoday_Laurens.git
   2c7565c..258b621  main -> main


05:30 11-12-2024

# Get in right directory

# Get up to date
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

# Run main file
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xb5dfabe0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='elo.somtoday.nl', port=443): Max retries exceeded with url: /services/webdav/calendarfeed/58405be0-5611-4aba-be66-9894a1009f12/4fc988ad-6d4d-4c2a-aaf0-8207665bf69b (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xb5dfabe0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laurens/Somtoday_Laurens/main.py", line 18, in <module>
    r = requests.get(url, allow_redirects=True)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='elo.somtoday.nl', port=443): Max retries exceeded with url: /services/webdav/calendarfeed/58405be0-5611-4aba-be66-9894a1009f12/4fc988ad-6d4d-4c2a-aaf0-8207665bf69b (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xb5dfabe0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

# Upload to Github
[main e985e62] 053011122024
 1 file changed, 3764 deletions(-)
 delete mode 100644 Final-File.ics
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


06:00 11-12-2024

# Get in right directory

# Get up to date
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

# Run main file
The file does not exist
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xb5e81be0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='elo.somtoday.nl', port=443): Max retries exceeded with url: /services/webdav/calendarfeed/58405be0-5611-4aba-be66-9894a1009f12/4fc988ad-6d4d-4c2a-aaf0-8207665bf69b (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xb5e81be0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laurens/Somtoday_Laurens/main.py", line 18, in <module>
    r = requests.get(url, allow_redirects=True)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='elo.somtoday.nl', port=443): Max retries exceeded with url: /services/webdav/calendarfeed/58405be0-5611-4aba-be66-9894a1009f12/4fc988ad-6d4d-4c2a-aaf0-8207665bf69b (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xb5e81be0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

# Upload to Github
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
